### ISSUE TITLE
Error Item topics - an attempt to get or set a field value in the empty dataset

### ISSUE THREAD

**Issue by autodataming** [jam-py/jamdocs#10]
Error Item topics - an attempt to get or set a field value in the empty dataset

I try to fix the https://github.com/jam-py/jamdocs/issues/9, and it failed and caused more serious problem.
I remove the directory in the server.
git clone the jamdocs project.
I restart the jamdocs server.  when i open the home page in the browser, it  will report the error (item topics - an attempt to get or set a field value in the empty dataset )

**Comment by autodataming** [comment]
the issue disappeared too.

**Comment by jam-py** [comment]
If error occurred on the server, please send me the server logs,
if on the client, open the browser debugger  (F12) and
copy and send me the call stack.
The same is with previous bug.

вт, 25 февр. 2020 г. в 17:12, autodataming <notifications@github.com>:

**Comment by autodataming** [comment]
Thank you . I have solved the problems.
I  rename the name of  directory, then solved the problem. and finally move the name to the previous name .
