### ISSUE TITLE
Error: Error binding parameter 3 - probably unsupported type.

### ISSUE THREAD

**Issue by autodataming** [jam-py/jamdocs#12]
```py conf.py
source_parsers = { '.md': CommonMarkParser}
source_suffix = ['.rst', '.md']
```
Error: Error binding parameter 3 - probably unsupported type.
 command: UPDATE "JAMDOC_PARAMETERS" SET "DELETED"=?, "DOC_PATH"=?, "OS_SEP"=?, "SOURCE_SUFFIX"=?, "PROJECT_NAME"=?, "IS_ACTIVE"=? WHERE "ID" = 2
 params: [0, u'/home/czq/pymolcn/source/conf.py', u'/', ['.rst', '.md'], u'pymolcn', 1]

I sovled the problem by modifing the conf.py

```py conf.py
source_parsers = { '.md': CommonMarkParser}
source_suffix = '.rst'
```

**Comment by jam-py** [comment]
Hi, thank you for the information.
I changed the app to support multiple source suffices


пт, 28 февр. 2020 г. в 16:33, autodataming <notifications@github.com>:
