### ISSUE TITLE
build error.  'ascii' codec can't encode characters in position 23-27: ordinal not in range(128)

### ISSUE THREAD

**Issue by autodataming** [jam-py/jamdocs#7]
when I deploy the jamdocs server with supervisor.
```conf
[program:sphinxadmin7]
directory = /home/czq/jamdocs
command = /home/czq/anaconda2/bin/python27ana server.py 52027
user = czq
autostart = true
autoresart = true
stderr_logfile = /var/log/sphinxadmin.stderr.log
stdout_logfile = /var/log/sphinxadmin.stdout.log
```
when I visit http://ip:52027 and click preview button. it show the error in the dialog.
```
'ascii' codec can't encode characters in position 23-27: ordinal not in range(128)

```
and  build information
```
/bin/sh: sphinx-build: 未找到命令
make: *** [html] 错误 127
 ```

if I directly run the command in the shell.
'''
/home/czq/anaconda2/bin/python27ana server.py 52027
'''      
It will not appear the above problem.

how to solve the problem?

**Comment by autodataming** [comment]
I revised the supervisord.conf
```
[supervisord]
environment=LANG="ru_RU.utf8", LC_LANG="ru_RU.UTF-8", LC_ALL="ru_RU.UTF-8"
```
when I start the jamdocs server, and click the preview button. It come across another problem.
[Errno 2] No such file or directory: 'make'

Finally, I give up use supervisor to manage the jamdocs server.

**Comment by jam-py** [comment]
Hello, I'll merge on the weekend.
There is too much work now

пт, 7 февр. 2020 г. в 06:09, autodataming <notifications@github.com>:

**Comment by jam-py** [comment]
Can you send more detailed log?

пт, 7 февр. 2020 г. в 09:46, Andrew Yushev <yushevaa@gmail.com>:

**Comment by autodataming** [comment]
nohup ./server.py &;   When I click preview button, it will appear the dialog "ascii coded ..." .But it will build success. So I ignore the error.
