### ISSUE TITLE
TypeError: Text exceeds the maximum allowed length - 10

### ISSUE THREAD

**Issue by autodataming** [jam-py/jamdocs#9]
TypeError: Text exceeds the maximum allowed length - 10.

The conf.py in my previous sphinx document was selected, it will raise the error.

![image](https://user-images.githubusercontent.com/7656130/75111841-24674280-5679-11ea-946c-1c48bd3c061f.png)

when I refresh the page(press F5 ), it will return to normal.

But when i double click the rst file, the rst editor will not appeared.

![image](https://user-images.githubusercontent.com/7656130/75111967-4f05cb00-567a-11ea-9036-4dd8a6d373e2.png)

**Comment by jam-py** [comment]
Hi,

I increased the project name field size.
But it seems it is some other field.
More debug information needed

The video below displays how to debug:
https://youtu.be/Dk9GfwigVdg

вс, 23 февр. 2020 г. в 15:06, autodataming <notifications@github.com>:

**Comment by autodataming** [comment]
I have notice the name in  tab is abnormal.

![图片](https://user-images.githubusercontent.com/7656130/75258452-6cc16480-5821-11ea-9a9c-a6a4d355722e.png)

the normal tab as the below.
![图片](https://user-images.githubusercontent.com/7656130/75258494-7cd94400-5821-11ea-919a-976f4b06f25a.png)
